### PR TITLE
feat: Add CoMPM model

### PR DESCRIPTION
**Pull request by FlPie**
### #11
Add CoMPM model
In test with using transformers.get_linear_schedule_with_warmup, seems models are not well learned. 
Currently not using any scheduler .

### Todo
Needs to use transformers.get_linear_schedule_with_warmup as scheduler which is used in paper.
More tests with larger epochs needed.

### CODE REVIEW

**Review by binlee52 — CHANGES_REQUESTED** [review]
It is recommended that you change the file name CoMPM_MELD_datamodule to MELD_datamodule. Because it can be used by other models.

Delete todo when refactoring. 

Other than that, it's so good.

**Comment by FlPie** [comment]
Since CoMPM requires two inputs(fore CoM & for PM), the data module for CoMPM must provide data in special format({input token, label, speaker token}). Also, the format of loading data used in the paper also seems unusual. 

So far, it seems right to keep CoMPM_MELD_loader. 

However, in the future, it seems better to separate MELD_loader and CoMPM_loader.

**Comment by binlee52** [comment]
Approve. Looks good so far!

**Comment by binlee52** [comment]
Close the issue because it has been merged.

**Pull request merged**
